package siv.type;

public enum ProsessNavn {
	KRAV_RYDDING_JOB,
	RYDD_MELDING_INN_JOB,
	RYDD_MELDING_UT_JOB,
	RYDD_FRAVAER_JOB,
	RYDD_INTERVJUER_JOB,
	BLAISE_TRIGGER_JOB,
	MELDING_INN_JOB,
	PAA_VENT_JOB,
	SEND_MELDING_UT_JOB,
	UTSENDT_CATI_JOB,
	LAAS_OPP_IO_JOB,
	RYDD_LONNSDATA_JOB,
	HENT_BLAISE_EVENTS_JOB,
	HENT_BLAISE_ENDRINGER_JOB;
}
